baseURL: https://tech.cloudmt.co.kr
title: í´ë¼ìš°ë“œë©”ì´íŠ¸ ê¸°ìˆ  ë¸”ë¡œê·¸ğŸ¦’
theme:
  - github.com/jonathanjanssens/hugo-casper3
permalinks: 
  post: /:2006/:01/:02/:filename
taxonomies:
  author: authors
  tag: tags
  category: categories
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: ""
          url: ""
          weight: 20
related:
  includeNewer: false
  indices:
  - category: categories
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: false

markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
        
googleAnalytics: UA-146594086-2
hasCJKLanguage: true
paginate: 10
params:
  # description: tech.cloudmr.co.kr
  nav_title: ğŸ‘¨â€ğŸ’»TECH BLOG
  copyright: Â© 2019-Present Cloudmate Co., Ltd.
  giscus:
    repo: cloudmatelabs/tech.cloudmt.co.kr
    repoId: MDEwOlJlcG9zaXRvcnkzMTYxNjcyNzI=
    category: Blog Comments
    categoryId: DIC_kwDOEthUaM4CUi7a
  footLogo: 
    path: /assets/images/CMLOGO_WHITE.png
    link: https://cloudmt.co.kr
  assets:
        favicon: /assets/favicon.ico
  background: /assets/images/background.png
  default_feature_image: /assets/images/post_cover.png
  DateFormat: 2006. 01. 02.
  facebook: https://fb.me/cloudmatekr
  github: https://github.com/cloudmatelabs
  mainSections:
    - post
  mainButtons:
    - name: ğŸ”—ìƒˆ ê¸°ìˆ  ë¸”ë¡œê·¸ë¡œ ì´ë™
      url: https://www.cloudmt.co.kr/TechBlog
  mainCategories:
    - Hands On
    - Tech
    - Column
    - Mate Story
