baseURL: https://tech.cloudmt.co.kr # 추후 수정 필요
title: CLOUDMATE Tech
theme:
  - github.com/adityatelange/hugo-PaperMod
permalinks: 
  post: /:2006/:01/:02/:filename
taxonomies:
  author: authors
  tag: tags
  category: categories

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Careers
          url: https://www.wanted.co.kr/company/14239
          weight: 15
        - name: cloudmt.co.kr
          url: https://cloudmt.co.kr
          weight: 20

params:
  homeInfoParams:
        Title: 클라우드메이트 기술 블로그
        Content: 클라우드메이트는 고객의 비즈니스 환경을 우선으로 생각하고, 사용자로서의 직접 경험을 공유합니다.
  description: 클라우드메이트는 고객의 비즈니스 환경을 우선으로 생각하고, 사용자로서의 직접 경험을 공유합니다.
  label:
        text: " "
        icon: /assets/images/CMLOGO_SHADOW.png
        iconHeight: 50
  assets:
        favicon: /assets/favicon.ico
  ShowShareButtons: true
  ShowPostNavLinks: true
  DateFormat: 2006. 01. 02.
  socialIcons:
    - name: github
      url: "https://github.com/mate365"
    - name: facebook
      url: https://fb.me/cloudmatekr
    - name: email
      url: mailto:contact@cloudmt.co.kr

