baseURL: /
title: í´ë¼ìš°ë“œë©”ì´íŠ¸ ê¸°ìˆ  ë¸”ë¡œê·¸ğŸ¦’
theme:
  - github.com/jonathanjanssens/hugo-casper3
permalinks: 
  post: /:2006/:01/:02/:filename
taxonomies:
  author: authors
  tag: tags
  category: categories
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: ""
          url: ""
          weight: 20
related:
  includeNewer: false
  indices:
  - category: categories
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: false

googleAnalytics: UA-146594086-2
hasCJKLanguage: true
paginate: 10
params:
  # description: tech.cloudmr.co.kr
  copyright: Â© 2019-Present CLOUDMATE Corp
  footLogo: 
    path: /assets/images/CMLOGO_WHITE.png
    link: https://cloudmt.co.kr
  assets:
        favicon: /assets/favicon.ico
  feature_image: /assets/images/default_post_cover.png
  DateFormat: 2006. 01. 02.
  facebook: https://fb.me/cloudmatekr
  github: https://github.com/mate365
  mainSections:
    - post
  mainButtons:
    - name: We Are Hiring!
      url: https://recruit.cloudmt.co.kr
  mainCategories:
    - Hands On
    - Tech
    - Column
    - Mate Story
