backend:
  name: github
  branch: main
  repo: cloudmatelabs/tech.cloudmt.co.kr
  base_url:  https://tech.cloudmt.co.kr
  auth_endpoint: /api/auth
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: static/img
locale: 'ko'

collections:
  - label: "저자"
    name: "authors"
    folder: "content/authors"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/_index"
    slug: "{{fields.slug}}"
    create: true
    editor:
      preview: true
    fields:
      - label: "저자 ID"
        name: "slug"
        widget: "string"
        pattern: ['^[a-z0-9-]+$', "공백 없이 영문 소문자, 숫자 및 하이픈만 허용"]
      - label: "저자 이름"
        name: "name"
        widget: "string"
      - label: "저자 사진"
        name: "photo"
        widget: "image"
      - label: "저자 소개"
        name: "body"
        widget: "markdown"
        required: false

  - label: "게시물"
    name: "post"
    folder: "content/post"
    media_folder: "images"
    public_folder: ""
    path: "{{slug}}/index"
    create: true
    editor:
      preview: true
    fields:
      # - label: "게시물ID"
      #   hint: "공백 없는 영문, 숫자, 하이픈 및 언더스코어로 작성. 예: hello_blog_post"
      #   name: "slug"
      #   widget: "string"
      #   pattern: ['^[A-Za-z0-9-_]+$', "공백 없이 영문, 숫자, 하이픈 및 언더스코어로만 허용"]
      - label: "제목"
        name: "title"
        widget: "string"
      - label: "작성자 ID"
        hint: "공백 없는 영문, 숫자, 하이픈 및 언더스코어로 작성. 예: gildong-hong"
        name: "authors"
        widget: "list"
        min: 1
        max: 1
        pattern: ['^[A-Za-z0-9-]+$', "content/authors 에 등록된 것으로 하나만 입력. 공백 없이 영문, 숫자 및 하이픈만 허용"]
      - label: "글 작성 일시"
        name: "date"
        widget: "datetime"
      - label: "커버 이미지"
        name: "feature_image"
        widget: "image"
        media_folder: "images"
        required: false
      - label: "카테고리"
        hint: 하나만 선택
        name: "categories"
        widget: "select"
        options: ["Hands On", "Tech", "Column", "Mate Story"]
        multiple: true
        min: 1
        max: 1
      - label: "태그"
        hint: 여러 개 입력시 쉼표로 구분
        name: tags
        widget: "list"
      - label: "내용"
        name: "body"
        widget: "markdown"